---
title: "Rworksheet_Regacho#2"
output:
  pdf_document: default
  html_document: default
---

---
title: "Rworksheet_Regacho#2"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#1. Create a vector using : operator
x <- -5:5
x
```

```{r}
x <- 1:7
x
```

```{r}
#2.* Create a vector using seq() function
seq(1, 3, by=0.2)
```

```{r}
#3. A factory has a census of its workers. There are 50 workers in total. The following list shows their ages:
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)

print(ages[3])

print(ages[c(2, 4)])

print(ages[-1])
```


```{r}
#4.Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).
x <- c("first"=3, "second"=0, "third"=9)
x
x[c("first", "third")]
#The Output shows only the first and third which the value is 3 and 9.
```

```{r}
#5. Create a sequence x from -3:2.
x <- -3:2
x
x[2] <- 0
x
#The output shows that the element [2] was replaced by 0.
```

```{r}
Month <- c("Jan", "Feb", "March" ,"April" , "May", "June")
Priceperliter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Liters <- c(25, 30, 40, 50, 10, 45)

fuel <- data.frame(Month, Priceperliter, Liters)
fuel

ave <- weighted.mean(Liters, Priceperliter)
ave
```

```{r}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), 
          var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)

```

```{r}
#8.
ranking <- c(1,2,3,4,5,6,7,8,9,10,
             11,12,13,14,15,16,17,18,19,20,
             21,22,23,24,25)

celeb <- c("Tom Cruise","Rolling Stones","Oprah Winfrey","U2","Tiger Woods",
           "Steven Spielberg","Howard Stern","50 Cent","Cast of the Sopranos","Dan Brown",
           "Bruce Springsteen","Donald Trump","Muhammad Ali","Paul McCartney","George Lucas",
           "Elton John","David Letterman","Phil Mickelson","J.K Rowling","Bradd Pitt",
           "Peter Jackson","Dr. Phil McGraw","Jay Leno","Celine Dion","Kobe Bryant")

pay <- c(67,90,225,110,90,
         332,302,41,52,88,
         55,44,55,40,233,
         34,40,47,75,25,
         39,45,32,40,31)

# Combine into a data frame
forbes <- data.frame(ranking, celeb, pay)
print(forbes)

### b. Modify J.K. Rowling → ranking = 15, pay = 90
forbes$ranking[forbes$celeb=="J.K Rowling"] <- 15
forbes$pay[forbes$celeb=="J.K Rowling"] <- 90


# Show updated data
print(forbes[forbes$celeb=="J.K Rowling" , ])
```
