---
title: "RWorksheet_Regacho#2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
x1 <- -5:5
print(x1)
```
```{r}
x2 <- 1:7
print(x2)
```
```{r}
x3 <- seq(1, 3, by=0.2)
print(x3)
```
```{r}
ages <- c(34,28,22,36,27,18,52,39,42,29,35,31,27,
          22,37,34,19,20,57,49,50,37,46,25,17,37,
          43,53,41,51,35,24,33,41,53,40,18,44,38,
          41,48,27,39,19,30,61,54,58,26,18)

print(ages[3])
print(ages[c(2,4)])
print(ages[-1])
```

```{r}
x4 <- c("first"=3, "second"=0, "third"=9)
print(names(x4))
print(x4[c("first","third")])

```

```{r}
x5 <- -3:2
print(x5) # Before modification
x5[2] <- 0
print(x5) # After modification
```

```{r}
### 6. Diesel fuel purchases of Mr. Cruz
month <- c("Jan","Feb","March","Apr","May","June")
price <- c(52.50,57.25,60.00,65.00,74.25,54.00)
liters <- c(25,30,40,50,10,45)

fuel <- data.frame(month, price, liters)
print(fuel)

# Average fuel expenditure (weighted mean)
avg_exp <- weighted.mean(price, liters)
print(avg_exp) # Output ≈ 60.41667

```

```{r}
### 7. Built-in dataset "rivers"

data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), 
          var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)

```

```{r}
```



